### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by WCjai** [kivy-garden/garden.cefpython#10]
hello, Iam trying to use this package, when I execute the code it shows this:

 Traceback (most recent call last):
   File "test.py", line 1, in <module>
     from kivy.garden.cefpython import CefBrowser, cefpython
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
   File "/home/wcjai/.local/lib/python3.8/site-packages/kivy/garden/__init__.py", line 180, in load_module
     return self._load_module(fullname, moddir)
   File "/home/wcjai/.local/lib/python3.8/site-packages/kivy/garden/__init__.py", line 183, in _load_module
     mod = imp.load_module(fullname, None, moddir,
   File "/usr/lib/python3.8/imp.py", line 244, in load_module
     return load_package(name, filename)
   File "/usr/lib/python3.8/imp.py", line 216, in load_package
     return _load(spec)
   File "/home/wcjai/.kivy/garden/garden.cefpython/__init__.py", line 64
     print 'Going to import {}'.format(libcef)
           ^
 SyntaxError: invalid syntax

and iam using the example code:
                             
from kivy.garden.cefpython import CefBrowser, cefpython
from kivy.app import App

class CefBrowserApp(App):
    def build(self):
        return CefBrowser(start_url='http://kivy.org')

CefBrowserApp().run()
    
cefpython.Shutdown()

I don't know what's wrong

**Comment by jegger** [comment]
The code does not seem to be ported to python3, as the syntax "print <string>" only exists in py2.
