### ISSUE TITLE
Garden package doesn't work

### ISSUE THREAD

**Issue by ghost** [kivy-garden/garden.cefpython#5]
When i try the example, i get a black screen.I'm using Manjaro Linux 64 bit. Here's the log:
[INFO   ] Kivy v1.8.1-dev
[INFO   ] [Python      ] v2.7.6 (default, Nov 26 2013, 12:52:49) 
[GCC 4.8.2]
[INFO   ] [Logger      ] Record log in /home/forgottenone/.kivy/logs/kivy_14-02-05_0.txt
[INFO   ] [Factory     ] 157 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[WARNING] Call to deprecated function **call** in /usr/lib/python2.7/site-packages/kivy/utils.py line 246.Called from /home/forgottenone/.kivy/garden/garden.cefpython/**init**.py line 33 by <module>().
[WARNING] Call to deprecated function **call** in /usr/lib/python2.7/site-packages/kivy/utils.py line 246.Called from /home/forgottenone/.kivy/garden/garden.cefpython/**init**.py line 40 by <module>().
Going to import /home/forgottenone/.kivy/garden/garden.cefpython/libs/linux64.py2/libcef.so
[DEBUG  ] [App         ] Loading kv <./cefbrowser.kv>
[DEBUG  ] [App         ] kv <./cefbrowser.kv> not found
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libpng warning: iCCP: known incorrect sRGB profile
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 800x600
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a0
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 2
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.0.2>
[INFO   ] [GL          ] OpenGL vendor <X.Org>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on AMD RV770>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImagePygame ] Load </usr/lib/python2.7/site-packages/kivy/data/glsl/default.png>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
sh: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF8)
cefpython: ------------------------------------------------------------
cefpython: Initialize() called
cefpython: CefExecuteProcess(): exitCode = -1
cefpython: CefInitialize()
[0205/083242:ERROR_REPORT:main_delegate.cc(448)] Check failed: false. Could not load cef.pak
[0205/083242:ERROR:zygote_host_impl_linux.cc(146)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

(process:4277): Gtk-WARNING *_: Locale not supported by C library.
        Using the fallback 'C' locale.
LaunchProcess: failed to execvp:
/home/forgottenone/.kivy/garden/garden.cefpython/libs/linux64.py2/subprocess
[0205/083242:ERROR:content_client.cc(91)] No data resource available for id 25003
[0205/083242:ERROR:content_client.cc(91)] No data resource available for id 25007
[0205/083242:ERROR:content_client.cc(91)] No data resource available for id 25004
cefpython: CreateBrowserSync() called
cefpython: navigateUrl: http://kivy.org
cefpython: CefBrowser::CreateBrowserSync()
cefpython: GetPyBrowser(): creating new PyBrowser, browserId=1
[0205/083242:ERROR_REPORT:render_widget_host_view_osr.cc(272)] Check failed: false. 
cefpython: CefBrowser::CreateBrowserSync() succeeded
cefpython: SendProcessMessage(): message=DoJavascriptBindings, arguments size=1
request_keyboard()
[INFO   ] [OSC         ] using <multiprocessing> for socket
[DEBUG  ] [Base        ] Create provider from mouse
[DEBUG  ] [Base        ] Create provider from probesysfs
[DEBUG  ] [ProbeSysfs  ] using probsysfs!
[DEBUG  ] [ProbeSysfs  ] found device: Logitech Gaming Mouse G600 at /dev/input/event2
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [MTD         ] Read event from </dev/input/event2>
[INFO   ] [Base        ] Start application main loop
[0205/083243:ERROR:child_process_launcher.cc(326)] Failed to launch child process
OnLoadingStateChange(): isLoading = False
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
     self.run()
   File "/usr/lib/python2.7/threading.py", line 763, in run
     self.__target(_self.**args, **self.__kwargs)
   File "/usr/lib/python2.7/site-packages/kivy/input/providers/mtdev.py", line 193, in _thread_run
     _device = Device(_fn)
   File "/usr/lib/python2.7/site-packages/kivy/lib/mtdev.py", line 131, in __init**
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 OSError: [Errno 13] Permission denied: '/dev/input/event2'

[INFO   ] [Base        ] Leaving application in progress...
cefpython: Shutdown()
cefpython: del g_pyBrowsers[1]

Note that if i install this package:https://code.google.com/p/cefpython/downloads/detail?name=cefpython3-29.2-ubuntu1204-64bit-setup.zip&can=2&q=, the kivy example in the package runs without a problem.

**Comment by cztomczak** [comment]
You are missing some of the binary files. The first error message from logs says about missing "cef.pak":

```
[0`205/083242:ERROR_REPORT:main_delegate.cc(448)] Check failed: false. Could not load cef.pak
```

**Comment by ghost** [comment]
Isn't it supposed to come with package?

**Comment by g5server** [comment]
I have the same problem.
Ubuntu 14.04

cefpython: ------------------------------------------------------------
cefpython: Initialize() called
cefpython: CefExecuteProcess(): exitCode = -1
cefpython: CefInitialize()

[0616/143810:ERROR_REPORT:main_delegate.cc(448)] Check failed: false. Could not load cef.pak

[0616/143810:ERROR:zygote_host_impl_linux.cc(146)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/media/jose/intercambio/Trabajos/cefpython/libs/linux64.py2/subprocess
[0616/143810:INFO:gpu_info_collector_linux.cc(78)] NVCtrl extension does not exist.
[0616/143810:ERROR:content_client.cc(91)] No data resource available for id 25003
[0616/143810:ERROR:content_client.cc(91)] No data resource available for id 25007
[0616/143810:ERROR:content_client.cc(91)] No data resource available for id 25004
cefpython: CreateBrowserSync() called
cefpython: navigateUrl: http://www.g5server.com
cefpython: CefBrowser::CreateBrowserSync()
cefpython: GetPyBrowser(): creating new PyBrowser, browserId=1
[0616/143810:ERROR_REPORT:render_widget_host_view_osr.cc(272)] Check failed: false. 
cefpython: CefBrowser::CreateBrowserSync() succeeded
cefpython: SendProcessMessage(): message=DoJavascriptBindings, arguments size=1
request_keyboard()
[0616/143810:ERROR:child_process_launcher.cc(326)] Failed to launch child process
OnLoadingStateChange(): isLoading = False

**Comment by gustavklopp** [comment]
Same problem of `Check failed: false. Could not load cef.pak`. So, I get a black screen unfortunately.

Even if 'cef.pak' is in my CEF folder at: cefpython3-31.2-linux64-setup/cefpython3

**Comment by ghost** [comment]
Try to put it into the directory where your script is executing / where you put the libcef.so

**Comment by gustavklopp** [comment]
Okay, that did the trick! 

Now... I have the second error listed by @forgottenone0 and @g5server :
`0205/083242:ERROR:zygote_host_impl_linux.cc(146)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.`

Lots of problem apparently for different programs using this "sandbox" but I haven't found a good working solution there.
I've got a /usr/lib/chromium-browser/chrome-sandbox. How do I use this?? (running it gives an error: `Usage: ./chrome-sandbox <renderer process> <args...>`)

**Comment by cztomczak** [comment]
@gustavklopp The sandbox error can be ignored.

**Comment by gustavklopp** [comment]
Okay, thanks! There's other things for me so:
`LaunchProcess: failed to execvp:
/home/gus/.kivy/garden/garden.cefpython/libs/linux64.py2/subprocess`
I don't understand what it is??

Full log:

```
[INFO              ] [Logger      ] Record log in /home/gus/.kivy/logs/kivy_15-07-26_10.txt
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2]
[INFO              ] [Factory     ] 176 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
[WARNING           ] Call to deprecated function __call__ in /home/gus/.Envs/python2.7_customKivy/local/lib/python2.7/site-packages/kivy/utils.py line 251.Called from /home/gus/.kivy/garden/garden.cefpython/__init__.py line 33 by <module>().
[WARNING           ] Call to deprecated function __call__ in /home/gus/.Envs/python2.7_customKivy/local/lib/python2.7/site-packages/kivy/utils.py line 251.Called from /home/gus/.kivy/garden/garden.cefpython/__init__.py line 40 by <module>().
Going to import /home/gus/.kivy/garden/garden.cefpython/libs/linux64.py2/libcef.so
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <3.0 Mesa 10.6.0-devel>
[INFO              ] [GL          ] OpenGL vendor <X.Org>
[INFO              ] [GL          ] OpenGL renderer <Gallium 0.4 on AMD KABINI>
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <1.30>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [GL          ] NPOT texture support is available
cefpython: ------------------------------------------------------------
cefpython: Initialize() called
cefpython: CefExecuteProcess(): exitCode = -1
cefpython: CefInitialize()
[0726/135146:ERROR:zygote_host_impl_linux.cc(146)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/home/gus/.kivy/garden/garden.cefpython/libs/linux64.py2/subprocess
cefpython: CreateBrowserSync() called
cefpython: navigateUrl: http://kivy.org
cefpython: CefBrowser::CreateBrowserSync()
cefpython: GetPyBrowser(): creating new PyBrowser, browserId=1
[0726/135147:ERROR_REPORT:render_widget_host_view_osr.cc(272)] Check failed: false. 
cefpython: CefBrowser::CreateBrowserSync() succeeded
cefpython: SendProcessMessage(): message=DoJavascriptBindings, arguments size=1
request_keyboard()
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Base        ] Start application main loop
[0726/135148:ERROR:child_process_launcher.cc(326)] Failed to launch child process
OnLoadingStateChange(): isLoading = False
```

Thanks a lot for your time!

**Comment by cztomczak** [comment]
Check that the subprocess executable exists at that location and that it
has execute permission. Make sure you are not missing any more binary files.

**Comment by gustavklopp** [comment]
It's working now! Thanks a lot!

In fact, I've decided to copy my entire downloaded folder from Cefpython: cefpython3-31.2-linux64-setup/cefpython3 into .kivy/garden/garden.cefpython/libs/linux64.py2.
It overwrites everything and apparently that's done the trick!

**Comment by susheel-smrt** [comment]
Im getting this error when I try to import kivy.garden.cefpython in my program.. please help me resolve this..

########
[INFO   ] [Logger      ] Record log in /home/susheel/.kivy/logs/kivy_17-09-21_4.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/lib/python2.7/dist-packages/kivy/garden/__init__.py", line 100, in load_module
     return self._load_module(fullname, moddir)
   File "/usr/lib/python2.7/dist-packages/kivy/garden/__init__.py", line 104, in _load_module
     ('', '', imp.PKG_DIRECTORY))
   File "/home/susheel/.kivy/garden/garden.cefpython/__init__.py", line 33, in <module>
     '{}{}.py{}'.format(platform(), BITS, PYVERSION)
 TypeError: 'str' object is not callable

**Comment by susheel-smrt** [comment]
@gustavklopp  .. from where did you copy ? please help I'm having the same error

**Comment by susheel-selvamani** [comment]
I have done copying stuff as mentioned by @gustavklopp .. even though I am getting this following error.. Please help me out..


###############


[ERROR  ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/logger.py", line 225, in emit
    self._configure()
  File "/usr/lib/python2.7/dist-packages/kivy/logger.py", line 183, in _configure
    FileHandler.fd = open(filename, 'w')
IOError: [Errno 13] Permission denied: u'/home/susheel/.kivy/logs/kivy_17-09-22_0.txt'
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
Going to import /home/susheel/.kivy/garden/garden.cefpython/libs/linux64.py2/libcef.so
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 17.0.7>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Haswell Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
request_keyboard()
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
_fix_select_boxes()
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
 Traceback (most recent call last):
   File "load_handler.pyx", line 58, in cefpython_py27.LoadHandler_OnLoadEnd (cefpython_py27.cpp:79614)
 TypeError: OnLoadEnd() got an unexpected keyword argument 'http_code'
 Traceback (most recent call last):
   File "load_handler.pyx", line 20, in cefpython_py27.LoadHandler_OnLoadingStateChange (cefpython_py27.cpp:78841)
 TypeError: OnLoadingStateChange() got an unexpected keyword argument 'is_loading'
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
go back
 Traceback (most recent call last):
   File "render_handler.pyx", line 63, in cefpython_py27.RenderHandler_GetViewRect (cefpython_py27.cpp:80945)
 TypeError: GetViewRect() got an unexpected keyword argument 'rect_out'
[INFO   ] [Base        ] Leaving application in progress...

**Comment by cztomczak** [comment]
@susheel-smrt You are using wrong version of CEF Python library. See this fork which supports latest CEF Python: https://github.com/allestuetsmerweh/garden.cefpython

**Comment by susheel-selvamani** [comment]
Thank you for the suggestion and when I try to use that package, I'm getting the following error. Pl. help me out.

#################
RESTART: /home/susheel/Downloads/garden.cefpython-master/examples/tabbed.py 
[ERROR  ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kivy/logger.py", line 225, in emit
    self._configure()
  File "/usr/lib/python2.7/dist-packages/kivy/logger.py", line 183, in _configure
    FileHandler.fd = open(filename, 'w')
IOError: [Errno 13] Permission denied: u'/home/susheel/.kivy/logs/kivy_17-10-12_0.txt'
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <4.5.0 NVIDIA 375.66>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <GeForce 830M/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <4.50 NVIDIA>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Going to import /home/susheel/.kivy/garden/garden.cefpython/libs/linux64.py2/libcef.so
 
 Traceback (most recent call last):
   File "/home/susheel/Downloads/garden.cefpython-master/examples/tabbed.py", line 15, in <module>
     from kivy.garden.cefpython import CEFBrowser
 ImportError: cannot import name CEFBrowser
