### ISSUE TITLE
Import error:

### ISSUE THREAD

**Issue by gustavklopp** [kivy-garden/garden.cefpython#7]
Hi,
I've got a problem during the import:

```
Going to import /home/gus/.kivy/garden/garden.cefpython/libs/linux64.py3/libcef.so
Unable to locate cefpython, trying to use package
 Traceback (most recent call last):
   File "/home/guido/BACKUP_gus/workspace/kivy_fix/cefpython_test.py", line 1, in <module>
     from kivy.garden.cefpython import CefBrowser, cefpython
   File "/home/gus/.Envs/python3_kivy/lib/python3.4/site-packages/kivy/garden/__init__.py", line 100, in load_module
     return self._load_module(fullname, moddir)
   File "/home/gus/.Envs/python3_kivy/lib/python3.4/site-packages/kivy/garden/__init__.py", line 104, in _load_module
     ('', '', imp.PKG_DIRECTORY))
   File "/home/gus/.Envs/python3_kivy/lib/python3.4/imp.py", line 245, in load_module
     return load_package(name, filename)
   File "/home/gus/.Envs/python3_kivy/lib/python3.4/imp.py", line 217, in load_package
     return methods.load()
   File "/home/gus/.kivy/garden/garden.cefpython/__init__.py", line 77, in <module>
     from cefpython3 import cefpython
 ImportError: No module named 'cefpython3'

```

Thanks a lot!

My config: garden 0.1.4, on Kivy 1.9.1. It's all installed in virtualenv by the way (don't know whether it's the problem but other addons seem to work)

**Comment by allestuetsmerweh** [comment]
You need to install cefpython first: http://code.google.com/p/cefpython/wiki/Download_CEF3_Linux

I once forked this repo to install cefpython automatically, but I'm not sure if it still works; haven't tested it for a long time, but here you go: https://github.com/allestuetsmerweh/garden.cefpython

**Comment by gustavklopp** [comment]
Okay, I didn't know. Thanks! 
Unfortunately, CEF is only python 2.x supported...

**Comment by hamedbb22** [comment]
i am using windows and have same problem
i install kivy.garden also
